defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
    address = ":80"
  
[api]
dashboard=true 

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "demo.res.ch"
watch = true